### ISSUE TITLE
CIS/TDDFT excited states

### ISSUE THREAD

**Issue by felixplasser** [nutjunkie/IQmol#40]
Hello, I tried setting up a TDDFT calculation in IQmol.

There is a box Advanced - Excited States - CIS. This allows to change a number of algorithmic settings. But it does not allow me to trigger the actual CIS calculation, which would need the keywords

~~~
   CIS_N_ROOTS  =  4
   CIS_SINGLETS  =  1
   CIS_TRIPLETS  =  1
~~~

So, I would still have to add these manually?

Thanks,
Felix

**Comment by nutjunkie** [comment]
Hi Felix,

In order to trigger a CIS/TD-DFT calculation, you should select CIS/TD-DFT from the Method combo box in the main set up panel.  This will set the necessary REM variables you referred to and also show a new panel below with additional related REMs.  The advanced panel contains those options I felt were unlikely to require changing for most users. 
![TDDFT](https://user-images.githubusercontent.com/2628598/86181214-f4710400-bb70-11ea-84c8-d9e44c83a18a.png)

**Comment by felixplasser** [comment]
Oh, thanks! Now I see what you are talking about. The thing that confused me is that the "Method" box in IQMol does not translate to the `Method` keyword in Q-Chem. But now I get it and it looks nice.
