### ISSUE TITLE
No queues found on server error with fresh 2.15.3 install - server misconfiguration?

### ISSUE THREAD

**Issue by Ecaloota** [nutjunkie/IQmol#64]
Hi,

I'm unable to submit jobs to the default QChem sever using the lastest pre-compiled 2.15.3bs dmg for Mac; when I try to submit a job, I receive a dialogue telling me that "No queues found on server" - another dialog then pops up, which prompts me to define resource limits for a queue, but no options are given in the drop-down for Queue.

I took a look at the server configurations via the Calculation -> Edit Servers menu, and nothing there looks out-of-place to me; when I tried to swap over to HTTPS on port 443 or port 80, I get SSL handshake failed errors. Do you think this could just be a server configuration issue that I can solve locally?

This is a fresh install of IQmol 2.1.5.3bs downloaded from the official webpage and running on MacOS 11.5.1. Let me know if you need any additional information.

**Comment by Ecaloota** [comment]
Just to follow up with additional information:

I downloaded and installed 2.15.2 and exported the working server config from that install, then imported it into 2.15.3: this works.

**Comment by nutjunkie** [comment]
I think at one point the I updated the connection enum and it rendered existing configurations incorrect.  Other than importing a server configuration, you can get around this by creating a new server using HTTP as the connection type and the default setup should work.

The handshake error is a different issue which is due to the SSL certificate expiring.  I thought this had been fixed, but until it is, you can get around the  issue by using HTTP rather than HTTPS as the connection type.

**Comment by Ecaloota** [comment]
Thanks @nutjunkie!
